driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt
      provision_command:
        - yum install make gcc -y
  - name: debian-9
    driver_config:
      provision_command:
        - apt-get install make gcc -y

provisioner:
  name: salt_solo
  formula: vagrant
  pillars-from-files:
    vagrant.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - vagrant
  state_top:
    base:
      "*":
        - vagrant

suites:
  - name: default
